name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: nx run gpt-chat-sdk:lint

      - name: Test
        run: nx run gpt-chat-sdk:test

      - name: Copy README from root to library
        run: |
          cd ./packages/gpt-chat-sdk
          npm run copy_docs_from_root

      - name: Build
        run: nx build gpt-chat-sdk

      - name: Copy DOCS files from root to dist
        run: |
          cd ./packages/gpt-chat-sdk
          npm run copy_docs_from_root_to_dist

      - name: Publish to NPM
        run: |
          cd ./dist/packages/gpt-chat-sdk
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Publish to GitHub Packages
        run: |
          cd ./dist/packages/gpt-chat-sdk
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> .npmrc
          npm publish --registry=https://npm.pkg.github.com/

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
