name: Publish @doc-gpt/chat Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx run chat:lint

      - name: Test
        run: npx nx run chat:test

      - name: Build
        run: npx nx build chat

      - name: Copy DOCS files from root to dist
        run: |
          cd ./packages/chat
          npm run copy_docs_from_root_to_dist

      - name: Publish to NPM (if needed)
        run: |
          cd ./dist/packages/chat
          touch .npmrc 
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}">>.npmrc
          echo "@doc-gpt:registry=https://registry.npmjs.org/">>.npmrc
          npm publish --access=public
        continue-on-error: true

      - name: Publish to GitHub Packages (if needed)
        run: |
          cd ./dist/packages/chat
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GH_TOKEN}}" >> .npmrc
          echo "@doc-gpt:registry=https://npm.pkg.github.com/">>.npmrc
          npm publish --registry=https://npm.pkg.github.com/
        continue-on-error: true
